### ISSUE TITLE
Coordinated egui 0.33→0.34 ecosystem upgrade (egui/eframe/egui_extras/egui_plot/egui-file-dialog) — needs code migration

### ISSUE THREAD

**Issue by KedoKudo** [ornlneutronimaging/NEREIDS#671]
## Summary
Dependabot opened four egui-stack bumps that **cannot be merged individually** — the egui ecosystem must move in lockstep, and `eframe` (which has no Dependabot PR) must bump too. This is a coordinated upgrade plus a code migration.

- #663 — `egui` 0.33.3 → 0.34.3
- #668 — `egui_extras` 0.33.3 → 0.34.3
- #661 — `egui_plot` 0.34.1 → 0.35.0
- #664 — `egui-file-dialog` 0.12.0 → 0.13.0
- **plus** `eframe` 0.33 → 0.34 (not in a Dependabot PR, but required)

## Why they must move together
Bumping `egui` to 0.34 while `eframe` still depends on egui 0.33 puts **two egui versions in the dependency graph**, causing type mismatches. Verified compile failure (from #663's CI):

```
error[E0308]: mismatched types
   expected `eframe::egui::ViewportBuilder`, found `egui::ViewportBuilder`
   note: there are multiple different versions of crate `egui` in the dependency graph
         (egui 0.33.3 and egui 0.34.3)
```

The workspace `Cargo.toml` already documents the lockstep rule (near the `egui-file-dialog` entry): `egui-file-dialog 0.12 ↔ egui 0.33`, `0.13 ↔ 0.34`, `0.14 ↔ 0.35`; and `egui_plot 0.35 ↔ egui 0.34`.

## Scope of work
**Manifest (workspace root `Cargo.toml`) — bump as one set:**
- `eframe` 0.33 → 0.34 (keep `persistence` + default features per the existing note)
- `egui` 0.33 → 0.34
- `egui_extras` 0.33 → 0.34 (keep `image`, `svg`)
- `egui_plot` 0.34 → 0.35
- `egui-file-dialog` 0.12 → 0.13
- (`egui-winit` / `accesskit` will follow `eframe`; currently locked at egui-winit 0.33.3, accesskit 0.21.1)

**Consumer crate:** `apps/gui` (all of the above are workspace deps used here).

**Code migration — egui 0.34 API.** Sites to review in `apps/gui/src`:
- `main.rs` — `eframe::NativeOptions`, `egui::ViewportBuilder`, `run_native`
- `theme.rs` — `configure_fonts`, `egui::Context` theme APIs (`apply_theme`, `resolve_dark_mode`)
- `file_dialog.rs` — `egui::Context` usage + `egui-file-dialog` 0.13 API
- `project.rs` — `save_modal(ctx: &egui::Context, …)`

Check the egui 0.34 and egui_plot 0.35 changelogs for the ViewportBuilder / fonts / plot API changes.

## Acceptance criteria
- Exactly one `egui` version in the graph (`cargo tree -d` shows no egui duplication).
- `cargo build --workspace --exclude nereids-python`, `cargo clippy … -D warnings`, and the GUI wheel build green; `cargo test --workspace --exclude nereids-python` green.
- Close #661, #663, #664, #668 as superseded by this coordinated PR.

## Context
Surfaced by the Dependabot config added in #651. Found while sweeping the resulting dependency PRs — routine bumps were merged; the egui stack was set aside because it needs a real lockstep upgrade + API migration.
