### ISSUE TITLE
Coordinated rand 0.9→0.10 ecosystem upgrade (rand_distr 0.6 + rand_chacha 0.10) — needs code migration

### ISSUE THREAD

**Issue by KedoKudo** [ornlneutronimaging/NEREIDS#670]
## Summary
Dependabot opened two rand-ecosystem bumps that **cannot be merged individually** — they are a single coordinated upgrade that also requires a code migration:

- #660 — `rand_distr` 0.5.1 → 0.6.0
- #665 — `rand_chacha` 0.9.0 → 0.10.0

Merging either alone breaks the build, so they were left for proper handling.

## Why they must move together
`rand_distr 0.6` pulls in `rand_core 0.10`, but if `rand`/`rand_chacha` stay on the 0.9 line, `ChaCha12Rng` does not implement the new `rand_core 0.10` `Rng` trait. Verified compile failure (from #660's CI):

```
error[E0277]: the trait bound `rand_chacha::ChaCha12Rng: rand_core::Rng` is not satisfied
   the trait `std::ops::DerefMut` is not implemented for `rand_chacha::ChaCha12Rng`
   = note: required for `rand_chacha::ChaCha12Rng` to implement `rand_core::TryRng`
   = note: required for `rand_chacha::ChaCha12Rng` to implement `rand_core::Rng`
   note: required by a bound in `rand_distr::Distribution::sample`
error: could not compile `nereids-fitting` (test "ic_closed_loop")
```

## Scope of work
**Manifest (workspace root `Cargo.toml`, currently lines ~79/83/84) — bump together:**
- `rand` 0.9 → 0.10
- `rand_chacha` 0.9 → 0.10
- `rand_distr` 0.5 → 0.6
- (add/align `rand_core` 0.10 if it needs to be explicit)

**Consumer crates:** `crates/nereids-fitting` (`rand`, `rand_chacha`, `rand_distr`), `crates/nereids-pipeline` (`rand`, `rand_distr`).

**Code migration — rand 0.10 API** (the 0.9→0.10 release reworked the `Rng`/`RngCore`/`SeedableRng` traits and the `Distribution::sample` bound). Known site:
- `crates/nereids-fitting/tests/ic_closed_loop.rs` — imports `rand::SeedableRng`, `rand_chacha::ChaCha12Rng`, `rand_distr::{Distribution, Normal}`.

**⚠️ Reproducibility caveat (important):** `ic_closed_loop.rs` (≈ lines 132–134) deliberately uses `ChaCha12Rng` *by name* for a stable seeded-noise stream, with a comment noting that a rand upgrade can silently change the noise realization. The 0.10 upgrade may shift the seeded RNG output → the closed-loop test's expected values/tolerances may need re-baselining. Confirm whether the stream changes and update the test intentionally (don't just loosen tolerances).

## Acceptance criteria
- `rand` / `rand_chacha` / `rand_distr` all on the 0.10 ecosystem (single `rand_core` 0.10 in the graph).
- `cargo build --workspace --exclude nereids-python` and `cargo test --workspace --exclude nereids-python` green (incl. `ic_closed_loop`), `cargo clippy … -D warnings` clean.
- Close #660 and #665 as superseded by this coordinated PR.

## Context
Surfaced by the Dependabot config added in #651. Discovered while sweeping the resulting dependency PRs — the routine bumps were merged; these two were set aside because they need real migration work.
